### ISSUE TITLE
Error while opening .db file

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TKlerx/android-sqlite-browser-for-eclipse#2] opened 2015-04-08 11:59 UTC
```
What steps will reproduce the problem?
1. Copied AndroidSQLiteBrowser_1.0.0.jar file into plugins folder of eclipse
2. Restarted the eclipse if it is already opened
3. Connected android device, goto DDMS perspective, select File Explorer, find 
the .db file in device memory then select "Open File in SQLite Browser" option 
in tools are of File Explorer.
4. You will automatically get another tab "Questoid SQLite Browser" opened and 
here you can find the below error log.

What is the expected output? What do you see instead?


What version of the product are you using? On what operating system?


Please provide any additional information below.

I got the below log under Questoid SQLite Browser

java.lang.NullPointerException
    at com.questoid.sqlitebrowser.view.SqliteBrowserView.createPartControl(SqliteBrowserView.java:83)
    at org.eclipse.ui.internal.ViewReference.createPartHelper(ViewReference.java:386)
    at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:240)
    at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:595)
    at org.eclipse.ui.internal.Perspective.showView(Perspective.java:2245)
    at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1145)
    at org.eclipse.ui.internal.WorkbenchPage$20.run(WorkbenchPage.java:3925)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:3922)
    at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:3898)
    at com.questoid.sqlitebrowser.SqliteBrowserPluginStartup$3$1.run(SqliteBrowserPluginStartup.java:150)
    at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:180)
    at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:150)
    at org.eclipse.swt.widgets.Display.syncExec(Display.java:4687)
    at com.questoid.sqlitebrowser.SqliteBrowserPluginStartup$3.run(SqliteBrowserPluginStartup.java:141)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$6.handleEvent(ActionContributionItem.java:452)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4169)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3758)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
```

Original issue reported on code.google.com by `gvenugop...@gmail.com` on 21 Jul 2014 at 11:41

**Comment by TKlerx** [comment] 2015-08-12 21:24
duplicate of #4. Should work now.

**Closed as completed by TKlerx** 2015-08-12 21:24 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
